In [2]:
%load_ext autoreload
%autoreload 2

In [1]:
import numpy as np
from wgomoku import (
    HeuristicGomokuPolicy, ThreatSearch, GomokuBoard, GomokuTools as gt, 
    Heuristics, UCT_Node, PolicyAdapter, GomokuEnvironment, GomokuState)

In [3]:
A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U = \
    1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
BLACK=0
WHITE=1

In [4]:
h = Heuristics(kappa=3.0)

In [5]:
stones = [(G,8), (F,7), (H,7), (F,9), (I,8), (H,8)]
env = GomokuEnvironment(heuristic=h, N=15, disp_width=6, initial_stones=stones)

In [7]:
state=env.reset()
root = UCT_Node(state, C=.5)

In [8]:
root.child_Q()

array([], dtype=float64)

In [9]:
priors = {(7, 6): 0.3228372544387403,
  (10, 9): 0.07913628746578324,
  (11, 10): 0.5980264580954766}

In [10]:
leaf = root.select_leaf()
leaf

Path: [None]

In [11]:
leaf.expand(priors)

In [12]:
leaf.child_priors

[0.3228372544387403, 0.5980264580954766, 0.07913628746578324]

In [13]:
leaf.child_moves

[(7, 6), (11, 10), (10, 9)]

In [14]:
leaf.child_total_value

array([0., 0., 0.], dtype=float32)

In [15]:
leaf.child_number_visits

array([0., 0., 0.], dtype=float32)

In [16]:
root, leaf, leaf.children

(Path: [None],
 Path: [None],
 [Path: [None, (7, 6)], Path: [None, (11, 10)], Path: [None, (10, 9)]])

In [17]:
leaf.children[0].pathid()

[None, (7, 6)]

In [18]:
leaf.backup(.4)

In [19]:
root.child_U()

array([0., 0., 0.])

In [20]:
qus = - root.child_Q() + root.C * root.child_U()
move = root.any_argmax(qus[0:]) # because we're starting at index 1
qus, move

(array([0., 0., 0.]), 2)

In [21]:
root.children[0].total_value

0.0

In [22]:
root.children[0].number_visits

0.0

In [23]:
## This should tell the algoritm to prefer pos=2 i.e. (11,10)
def leaf_value(leaf):
    path=[leaf.pos]
    while leaf.parent:
        path=[leaf.parent.pos] + path
        leaf = leaf.parent
    return (sum(path[1:])+1.0)/10 

In [24]:
num_reads=100
for i in range(num_reads):
    leaf = root.select_leaf()
    leaf.expand(priors)
    leaf.backup(leaf_value(leaf))

In [25]:
for c in root.children:
    print(c.number_visits)

3.0
5.0
89.0


In [26]:
qus = - root.child_Q() + root.C * root.child_U()
move = root.any_argmax(qus[0:]) # because we're starting at index 1
qus, move

(array([0.70971435, 0.71992576, 0.75495   ], dtype=float32), 2)

In [27]:
root.number_visits

97.0

In [28]:
root.children[1].game_state.to_play

-1