# Train the policy from sufficient data

---
### @Wolfie: START HERE: NOT YET WORKING
---

In [ ]:
BOARD_SIZE=15

---
# Training a neural network with Selfplay data

In [23]:
from aegomoku.gomoku_model import NeuralNetAdapter

the_model = NeuralNetAdapter( BOARD_SIZE+ 2)
the_model.policy.summary()
sample = np.expand_dims(examples[0][0], axis=0).astype(float)
print(sample.shape)

Model: "gomoku_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 initial (Conv2D)            multiple                  11648     
                                                                 
 potential_0 (Conv2D)        multiple                  123936    
                                                                 
 potential_1 (Conv2D)        multiple                  123936    
                                                                 
 potential_2 (Conv2D)        multiple                  123936    
                                                                 
 potential_3 (Conv2D)        multiple                  123936    
                                                                 
 potential_4 (Conv2D)        multiple                  123936    
                                                                 
 policy_aggregator (Conv2D)  multiple                 

2022-08-03 21:20:51.558907: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [24]:
the_model.policy(sample, debug=True)

Potential: 3073.421875
Value Head: -22.637210845947266
Policy Head: 0.3489210903644562


(<tf.Tensor: shape=(1, 225), dtype=float32, numpy=
 array([[0.00443726, 0.00443726, 0.00443726, 0.00443726, 0.00443726,
         0.00443726, 0.00443726, 0.00443726, 0.00443726, 0.00443726,
         0.00443726, 0.00443726, 0.00443726, 0.00443726, 0.00443726,
         0.00443726, 0.00443726, 0.00443726, 0.00443726, 0.00443726,
         0.00443726, 0.00443726, 0.00443726, 0.00443726, 0.00443726,
         0.00443726, 0.00443726, 0.00443726, 0.00443726, 0.00443726,
         0.00449675, 0.00443726, 0.00443726, 0.00443726, 0.00443726,
         0.00443726, 0.00443726, 0.00443726, 0.00443726, 0.00443726,
         0.00443726, 0.00443726, 0.00443726, 0.00443726, 0.00443726,
         0.00460492, 0.00443726, 0.00505739, 0.00443726, 0.00443726,
         0.00443726, 0.00443726, 0.00443726, 0.00443726, 0.00443726,
         0.00443726, 0.00443726, 0.00443726, 0.00443726, 0.00443726,
         0.00454716, 0.00443726, 0.00484231, 0.00443726, 0.00443726,
         0.00443726, 0.00443726, 0.00443726, 0.00443

In [35]:
the_model.train(examples[:10], epochs_per_train=2)

Epoch: 1, Loss: 5.380550384521484
Epochs: 2, Loss: 5.380550384521484


# Did the policy learn?

In [33]:
ex=examples[-1]
print(len(ex), ex[0].shape, ex[2])
print((np.array(ex[1]) * 100).reshape((15, 15)).astype(int))
gt.print_channels(ex[0])

3 (17, 17, 3) 1.0
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0 100   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]]
shape: (17, 17, 3)
[[3 3 3 3 3 3 3 3

In [34]:
p, v = the_model.predict(np.expand_dims(ex[0], axis=0).astype(float), debug=True)
print((p*100).numpy().reshape((15, 15)).astype(int))
print()
print(f"Value: {v}")

Potential: 18080.5234375
Value Head: -212.93588256835938
Policy Head: 0.0
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]

Value: [[-0.00454056]]


In [36]:
the_model = NeuralNetAdapter( BOARD_SIZE+ 2)

In [37]:
examples_file = 'temperature/checkpoint_0.pth.tar.examples'

In [38]:
from pickle import Unpickler

with open(examples_file, "rb") as f:
    examples = Unpickler(f).load()


In [39]:
ex = examples[0][-10]

In [40]:
ex[0].shape

(17, 17, 3)