In [3]:
from aegomoku.game_data import read_training_data
import random
import numpy as np
import tensorflow as tf


In [2]:
BOARD_SIZE=15
filename = "rawdata.pickle"
examples = read_training_data(filename, BOARD_SIZE)
len(examples), len(examples[0]), examples[0][0].shape

(20320, 3, (17, 17, 3))

In [5]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'),
 PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]

In [10]:
from aegomoku.policies.heuristic_policy import HeuristicPolicy
from aegomoku.gomoku_model import NeuralNetAdapter
policy = HeuristicPolicy(BOARD_SIZE)
the_model = NeuralNetAdapter(BOARD_SIZE + 2)
the_model.policy.compile()

/home/wgiersche/.local/share/virtualenvs/DeepGomoku-yQC4gx5q/lib/python3.8/site-packages/numpy/core/fromnumeric.py:2009: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = asarray(a).shape


In [14]:
sample = np.expand_dims(examples[5][0], axis=0).astype(float)
print(sample.shape)
sample = np.squeeze(sample)
p, v = policy(sample)

(1, 17, 17, 3)


In [16]:
import aegomoku.tools as gt
gt.print_channels(sample)

shape: (17, 17, 3)
[[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 1. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 0. 2. 1. 1. 1. 0. 2. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 0. 1. 1. 2. 2. 0. 0. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 0. 2. 1. 1. 2. 0. 0. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 0. 1. 2. 2. 2. 0. 0. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 0. 0. 2. 1. 0. 0. 0. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]]


In [18]:
p.shape

(15, 15)

In [22]:
p = tf.reshape(p, (1, 15, 15, 1))

In [23]:
pad = tf.keras.layers.ZeroPadding2D(
    padding=(1, 1), data_format=None,
)

In [24]:
pad(p)

<tf.Tensor: shape=(1, 17, 17, 1), dtype=float32, numpy=
array([[[[0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00],
         [0.00000000e+00]],

        [[0.00000000e+00],
         [3.06460168e-09],
         [3.06460168e-09],
         [3.06460168e-09],
         [3.06460168e-09],
         [3.06460168e-09],
         [3.06460168e-09],
         [3.06460168e-09],
         [3.06460168e-09],
         [3.06460168e-09],
         [3.06460168e-09],
         [3.06460168e-09],
         [3.06460168e-09],
         [3.06460168e-09],
         [3.06460168e-09],
         [3.06460168e-09],
         [0.00000000e+00]],

        [[0.00000000e+