In [1]:
%load_ext autoreload
%autoreload 2

In [11]:
from alphazero.gomoku_board import GomokuBoard

In [12]:
BOARD_SIZE=15

In [13]:
stones = "H8I8"
stones = "C11F9E9G8F7G7G9H8I8H7I6I9F6H6H9I5J4"
#stones = "C11 F9 E9 G8 F7 G7 G9 H8 I8 H7 I6 I9 F6 H6 H9 I5 J4 J7 K7 D10 H4 G5 K4 I4 K5 K6 L6 I3 M7 N8 M5 J8 F5"

In [14]:
board = GomokuBoard(15, stones)
s = board.math_rep

In [15]:
board.plot()

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  X  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 9    .  .  .  .  X  O  X  X  O  .  .  .  .  .  .    
 8    .  .  .  .  .  .  O  O  X  .  .  .  .  .  .    
 7    .  .  .  .  .  X  O  O  .  .  .  .  .  .  .    
 6    .  .  .  .  .  X  .  O  X  .  .  .  .  .  .    
 5    .  .  .  .  .  .  .  .  O  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  .  . [X] .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O


In [16]:
from domoku.policies.heuristic_policy import HeuristicPolicy

d = HeuristicPolicy(board_size=BOARD_SIZE, cut_off=.1)

/Users/wgiersche/.local/share/virtualenvs/DeepGomoku-cXtJ_EtM/lib/python3.10/site-packages/numpy/core/fromnumeric.py:2007: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = asarray(a).shape


In [17]:
board.print_pi(lambda s: d(s)[0])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   2   3   4   3   1   0   0   0   0   0   0   0   0]
 [  0 494   4  10  11   8   6   2   0   2   1   2   0   0   0]
 [  0   4   0 771 256 508   9   5   1   3 527   2   1   0   0]
 [  0   7  13 513 537  16 504   5   1 529   5   5   0   0   0]
 [  0   5  15  19   0   0   0   0   0   3   8 239   1   0   0]
 [  0   5  12  20  18  11   0   0   0   8 240   3   0   0   0]
 [  0   3  10  17  21   0   0   0   7 501 251   1   0   0   0]
 [  0   2   6  15  18   0   3   0   0 484 499   0   1   0   0]
 [  0   0   4   8  10 745 251 999   0 488 250   5   0   0   0]
 [  0   0   1   2   5 493 237 760   2   0   6   1   1   0   0]
 [  0   0   0   0   0   0 246   0   0   4   1   1   0   0   0]
 [  0   0   0   0   0 246   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]]


In [18]:
board.act('H5')
board.print_pi(lambda s: d(s)[0])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   8   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   6   3   9   0   0   0   0   3   0   0   0   0]
 [  0   0   0   9   3   0   9   0   0   3   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   2   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   2   9   2   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   5   9   0   0   0   0]
 [  0   0   0   0   0  14   5   0   0   8   5   0   0   0   0]
 [  0   0   0   0   0  11   0 998   0   0   0   0   0   0   0]
 [  0   0   0   0   2   0   2   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   2   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]]


In [33]:
next_move = d.get_advisable_actions(s)[0]
next_move = board.Stone(next_move)
next_move

H4

In [34]:
board.act('C7')

C11 F9 E9 G8 F7 G7 G9 H8 I8 H7 I6 I9 F6 H6 H9 I5 J4 H5 C7

In [35]:
board.plot()
board.print_pi(lambda s: d(s)[0])

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  X  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 9    .  .  .  .  X  O  X  X  O  .  .  .  .  .  .    
 8    .  .  .  .  .  .  O  O  X  .  .  .  .  .  .    
 7    .  . [X] .  .  X  O  O  .  .  .  .  .  .  .    
 6    .  .  .  .  .  X  .  O  X  .  .  .  .  .  .    
 5    .  .  .  .  .  .  .  O  O  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  .  .  X  .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O
[[  0   0   0   0   0   0   0   

In [36]:
d(s)[1]

<tf.Tensor: shape=(), dtype=float64, numpy=0.9298174518079388>