# Pass-or-Not for the TopologicalValuePolicy

In [4]:
import tensorflow as tf
import numpy as np

In [15]:
threshold = -0.04
k = 10./ threshold

"""
Here's the reasoning: Hard sigmoid is 0 below -2.5. With a bias of -200 and the phase amplifier of 187.5, the matching
phase will bring the output to -12.5, that is 10 left to go. Faktor k is chosen so that any value above threshold makes
the sum exceed -2.5, hence rapidly increasing the probability of a pass move
"""
pass_or_not = tf.keras.layers.Dense(
    units=1, kernel_initializer=tf.constant_initializer([0., 0., 187.5, 0., 187.5, 0., 0., k]),
    bias_initializer=tf.constant_initializer(-200.),
    activation=tf.keras.activations.hard_sigmoid
)

In [34]:
input = np.array([[0, 0, 0, 0, 1, 0, 0, -0.03]]).astype(float)
pass_or_not(input)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.]], dtype=float32)>

In [35]:
input

array([[ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  , -0.03]])

In [37]:
np.append(input, [2.0])

array([ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  , -0.03,  2.  ])

In [38]:
output = pass_or_not(input)

In [39]:
output

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.]], dtype=float32)>

In [48]:
tf.keras.layers.Concatenate(axis=1)([output, tf.constant([[0.]])])

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0., 1.]], dtype=float32)>