In [12]:
from domoku import data
import domoku.jupyter_tools as jt
from domoku.tools import GomokuTools as gt

In [13]:
stones = 'B2D4D2'

In [14]:
state = data.create_nxnx4(size=5, stones=stones)

In [15]:
jt.print_bin(state, True)

shape: (5, 5, 4)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 2. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
all_stones_t = [data.transform(gt.string_to_stones(stones), 5, rot, ref)
                for rot in range(4)
                for ref in [False, True]]

In [20]:
for i in range(8):
    jt.print_bin(data.create_nxnx4(5, stones = all_stones_t[i]), True)

shape: (5, 5, 4)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 2. 0.]
 [0. 0. 0. 0. 0.]]
shape: (5, 5, 4)
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 2. 0.]
 [0. 0. 0. 0. 0.]]
shape: (5, 5, 4)
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 2. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0.]]
shape: (5, 5, 4)
[[0. 0. 0. 0. 0.]
 [0. 2. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
shape: (5, 5, 4)
[[0. 0. 0. 0. 0.]
 [0. 2. 0. 2. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
shape: (5, 5, 4)
[[0. 0. 0. 0. 0.]
 [0. 2. 0. 2. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]
shape: (5, 5, 4)
[[0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]
shape: (5, 5, 4)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 2. 0.]
 [0. 0. 0. 0. 0.]]
