# Heuristic Policy from Topological Value


---

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from aegomoku.utils import expand
from aegomoku.utils import analyse_board
from aegomoku.policies.heuristic_policy import HeuristicPolicy
from aegomoku.gomoku_board import GomokuBoard

In [3]:
BOARD_SIZE = 15

In [8]:
from aegomoku.policies.topological_value import TopologicalValuePolicy

policy = TopologicalValuePolicy(kappa_s=6, kappa_d=5)
st = 'H8G7I7'
board = GomokuBoard(board_size=BOARD_SIZE, stones = st)

In [9]:
board.plot()

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 9    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 8    .  .  .  .  .  .  .  X  .  .  .  .  .  .  .    
 7    .  .  .  .  .  .  O  . [X] .  .  .  .  .  .    
 6    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 5    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O


In [10]:
state = board.canonical_representation()
probs, v = policy.evaluate(state)
print((np.reshape(probs, (BOARD_SIZE, BOARD_SIZE))*999).astype(int))
print(v)
advice = policy.get_advisable_actions(state)
print([board.Stone(i) for i in advice])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   2   0   0   0   2   0   0   0   2   0   0   0]
 [  0   0   2   0  17   0   2   2   2   0   2   0   2   0   0]
 [  0   0   0   2   0  27   2   3   2   2   0   2   0   0   0]
 [  0   0   0   0   3   0 417   3   4   0   3   0   0   0   0]
 [  0   0   0   2   2  42  47   0   5   5   2   2   0   0   0]
 [  0   0   2   2   2   2   0  32   0   2   2   2   2   0   0]
 [  0   0   0   0   0   2   3  64   3  37   0   0   0   0   0]
 [  0   0   0   0   2   0  37   2  37   0  27   0   0   0   0]
 [  0   0   0   2   0   2   2   2   2   2   0  17   0   0   0]
 [  0   0   2   0   2   0   2   0   2   0   2   0   2   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]]
-0.14276334338585456
[E11, F10, G9, F8, G8, I8, J8, H7

In [11]:
state = board.canonical_representation()
probs, v = policy.evaluate2(state)
print((np.reshape(probs, (BOARD_SIZE, BOARD_SIZE))*999).astype(int))
print(v)
advice = policy.get_advisable_actions(state)
print([board.Stone(i) for i in advice])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   2   0   0   0   2   0   0   0   2   0   0   0]
 [  0   0   2   0  17   0   2   2   2   0   2   0   2   0   0]
 [  0   0   0   2   0  27   2   3   2   2   0   2   0   0   0]
 [  0   0   0   0   3   0 417   3   4   0   3   0   0   0   0]
 [  0   0   0   2   2  42  47   0   5   5   2   2   0   0   0]
 [  0   0   2   2   2   2   0  32   0   2   2   2   2   0   0]
 [  0   0   0   0   0   2   3  64   3  37   0   0   0   0   0]
 [  0   0   0   0   2   0  37   2  37   0  27   0   0   0   0]
 [  0   0   0   2   0   2   2   2   2   2   0  17   0   0   0]
 [  0   0   2   0   2   0   2   0   2   0   2   0   2   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]]
-0.14276335
[E11, F10, G9, F8, G8, I8, J8, H7, H6, J6,

In [8]:
import tensorflow as tf
self = policy
y = self.detector(expand(state))
y.shape

TensorShape([1, 17, 17, 40])

In [9]:
y = tf.math.pow(y, self.kappa_s)
y.shape

TensorShape([1, 17, 17, 40])

In [10]:
y = self.sum_s(y)
y.shape

TensorShape([1, 17, 17, 8])

In [11]:
print(np.squeeze(y)[:, :, 7])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [12]:
y = tf.math.pow(y, self.kappa_d/self.kappa_s)
y

<tf.Tensor: shape=(1, 17, 17, 8), dtype=float32, numpy=
array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0

In [13]:
y = self.sum_d(y)
y = tf.math.pow(y, 1 / self.kappa_d)
y

<tf.Tensor: shape=(1, 17, 17, 2), dtype=float32, numpy=
array([[[[0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ]],

        [[0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.       , 0.       ],
         [0.      

In [14]:
print((np.squeeze(y)[:, :, 1] *99).astype(int))

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0  99   0   0   0  99   0   0   0  99   0   0   0   0]
 [  0   0   0   0   0 111   0   0 111   0   0 111   0   0   0   0   0]
 [  0   0   0   0   0   0 118   0 118   0 118   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 124 124 124   0   0   0   0   0   0   0]
 [  0   0   0   0  99 111 118 124   0 124 118 111  99   0   0   0   0]
 [  0   0   0   0   0   0   0 124 124 124   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 118   0 118   0 118   0   0   0   0   0   0]
 [  0   0   0   0   0 111   0   0 111   0   0 111   0   0   0   0   0]
 [  0   0   0   0  99   0   0   0  99   0   0   0  99   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 

In [15]:
y = self.p_v(y)
y

<tf.Tensor: shape=(1, 17, 17, 2), dtype=float32, numpy=
array([[[[ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ]],

        [[ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       ],
         [ 0.       ,  0.       

In [16]:
print((np.squeeze(y)[:, :, 1] *9).astype(int))

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0  -9   0   0   0  -9   0   0   0  -9   0   0   0   0]
 [  0   0   0   0   0 -10   0   0 -10   0   0 -10   0   0   0   0   0]
 [  0   0   0   0   0   0 -10   0 -10   0 -10   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 -11 -11 -11   0   0   0   0   0   0   0]
 [  0   0   0   0  -9 -10 -10 -11   0 -11 -10 -10  -9   0   0   0   0]
 [  0   0   0   0   0   0   0 -11 -11 -11   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 -10   0 -10   0 -10   0   0   0   0   0   0]
 [  0   0   0   0   0 -10   0   0 -10   0   0 -10   0   0   0   0   0]
 [  0   0   0   0  -9   0   0   0  -9   0   0   0  -9   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 

In [32]:
p, v = y[:, :, :, 0], y[:, :, :, 1]
p = self.peel(tf.expand_dims(p, -1))
v = self.peel(tf.expand_dims(v, -1))
p.shape, v.shape

(TensorShape([1, 15, 15, 1]), TensorShape([1, 15, 15, 1]))

In [33]:
print((np.squeeze(p) *9).astype(int))

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  9  0  0  0  9  0  0  0  9  0  0  0]
 [ 0  0  0  0 10  0  0 10  0  0 10  0  0  0  0]
 [ 0  0  0  0  0 10  0 10  0 10  0  0  0  0  0]
 [ 0  0  0  0  0  0 11 11 11  0  0  0  0  0  0]
 [ 0  0  0  9 10 10 11  0 11 10 10  9  0  0  0]
 [ 0  0  0  0  0  0 11 11 11  0  0  0  0  0  0]
 [ 0  0  0  0  0 10  0 10  0 10  0  0  0  0  0]
 [ 0  0  0  0 10  0  0 10  0  0 10  0  0  0  0]
 [ 0  0  0  9  0  0  0  9  0  0  0  9  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]


In [36]:
probs = tf.reshape(p, (-1, 225))

In [37]:
probs = tf.keras.layers.Softmax()(self.policy_stretch * probs)
probs.shape

TensorShape([1, 225])

In [40]:
print((np.squeeze(tf.reshape(probs, (15, 15))) *999).astype(int))

[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1 14  1  1  1 14  1  1  1 14  1  1  1]
 [ 1  1  1  1 18  1  1 18  1  1 18  1  1  1  1]
 [ 1  1  1  1  1 21  1 21  1 21  1  1  1  1  1]
 [ 1  1  1  1  1  1 24 24 24  1  1  1  1  1  1]
 [ 1  1  1 14 18 21 24  1 24 21 18 14  1  1  1]
 [ 1  1  1  1  1  1 24 24 24  1  1  1  1  1  1]
 [ 1  1  1  1  1 21  1 21  1 21  1  1  1  1  1]
 [ 1  1  1  1 18  1  1 18  1  1 18  1  1  1  1]
 [ 1  1  1 14  1  1  1 14  1  1  1 14  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]]


In [9]:
policy.value_gauge

0.2

In [41]:
tf.math.reduce_sum(v, axis=None)

<tf.Tensor: shape=(), dtype=float32, numpy=-36.66656>

In [45]:
value = tf.nn.tanh(self.value_gauge * tf.math.reduce_sum(v, axis=None))
print(value*self.value_stretch)

tf.Tensor(-0.031249974, shape=(), dtype=float32)


In [ ]:
probs = tf.keras.layers.Softmax()(self.policy_stretch * p)

In [ ]:
value = tf.nn.tanh(self.value_stretch * tf.math.reduce_sum(v))

In [48]:
self.value(expand(state))


KeyboardInterrupt



In [20]:
st = 'H8G9I9I8G7F6H7F7H6F8H9H10H5F9H4F5'
board = GomokuBoard(board_size=BOARD_SIZE, stones = st)
board.plot()
state = board.canonical_representation()
probs, v = policy.evaluate(state)
print((np.reshape(probs, (BOARD_SIZE, BOARD_SIZE))*999).astype(int))
print(v)
print(f"Advisable: {[board.Stone(i) for i in policy.get_advisable_actions(state)]}")

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  O  .  .  .  .  .  .  .    
 9    .  .  .  .  .  O  O  X  X  .  .  .  .  .  .    
 8    .  .  .  .  .  O  .  X  O  .  .  .  .  .  .    
 7    .  .  .  .  .  O  X  X  .  .  .  .  .  .  .    
 6    .  .  .  .  .  O  .  X  .  .  .  .  .  .  .    
 5    .  .  .  .  . [O] .  X  .  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  X  .  .  .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O
[[  0   0   0   0   0   0   0   

In [19]:
policy.get_winner(state)

1

In [12]:
board = GomokuBoard(BOARD_SIZE, stones=stones)
board.plot()

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 9    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 8    .  .  .  .  .  .  . [X] .  .  .  .  .  .  .    
 7    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 6    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 5    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O


In [13]:
inputs = expand(board)
inputs.shape

(1, 17, 17, 3)

In [14]:
res = detector(expand(board))
res = np.squeeze(res)
res.shape

(17, 17, 40)

In [15]:
print(np.sum(res, axis=2))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0. 2. 0. 0. 2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 0. 3. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 4. 4. 4. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 3. 4. 0. 4. 3. 2. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 4. 4. 4. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 0. 3. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0. 2. 0. 0. 2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


As expected, for a single stone on the board, we count 4 possible lines right next to the stone, and one less for each increasing distance.

## Line Topology

Any two different lines are considered orthogonal, even the five geometrically parallel lines. The Euclidean square is replaced by a power of 6

It appears that a power of 6 captures the expected value topology: two intersecting lines of 2 are almost as valuable as a single line of 3, and so on.

In [16]:
import numpy as np
line = np.array([1., 2., 2., 2., 1.])
line = np.array([1., 2., 3., 3.])

In [17]:
print(np.power(sum(line ** 6),1./6))
print(np.power(sum(line * line * line * line * line * line) + sum(line * line * line * line * line * line),1./6))

3.3919542339280846
3.807339897186568


Two lines of three add to something between 3 and 4

In [18]:
np.power(3**6 + 3 **6, 1./6)

3.3673861449281186

In [19]:
line ** 3

array([ 1.,  8., 27., 27.])

In [20]:
reshaped.shape

(9, 9, 3, 40)

In [21]:
for d in range(5):
    print(reshaped[:, :, 0, 4 + 8 * d])
    print()

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]]

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.

In [22]:
for c in range(3):
    print(reshaped[:, :, c, 4])
    print()

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]]

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.]]

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -5.

In [23]:
res.shape

(17, 17, 40)

In [24]:
peel = tf.keras.layers.Conv2D(
    filters=1, kernel_size=(3, 3),
    kernel_initializer=tf.constant_initializer([
        [[0., 0., 0.], [0., 1., 0.], [0., 0., 0.]]
    ]),
    bias_initializer=tf.constant_initializer(0.),
    trainable=False)

In [25]:
res = detector(expand(board))
res.shape

TensorShape([1, 17, 17, 40])

The stone is now on the 'other' channel

In [26]:
layer = 20
print(np.squeeze(peel(tf.expand_dims(res[:, :, :, layer], -1))))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Fourty different images

In [27]:
v = []
for layer in range(40):
    v.append(np.squeeze(peel(tf.expand_dims(res[:, :, :, layer], -1))))

In [28]:
print(v[20])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [29]:
def v_(s, c, d):
    return v[8 * s + 4 * c + d]

In [30]:
print(v_(s=2, c=1, d=0))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [31]:
def v__(d,c):
    return sum( [ v_(s, c, d) ** 6 for s in range(5) ])**(1/6.)

In [32]:
v__(d=3, c=1)

array([[0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       , 0.       , 1.       ,
        0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       , 1.122462 , 0.       ,
        0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       

In [33]:
def v___(c):
    return sum([v__(d, c) ** 5 for d in range(4)]) ** (1/5.0)

In [34]:
v1 = v___(c=1)/32.
print((v1*1000).astype(int))

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 31  0  0  0 31  0  0  0 31  0  0  0]
 [ 0  0  0  0 35  0  0 35  0  0 35  0  0  0  0]
 [ 0  0  0  0  0 37  0 37  0 37  0  0  0  0  0]
 [ 0  0  0  0  0  0 39 39 39  0  0  0  0  0  0]
 [ 0  0  0 31 35 37 39  0 39 37 35 31  0  0  0]
 [ 0  0  0  0  0  0 39 39 39  0  0  0  0  0  0]
 [ 0  0  0  0  0 37  0 37  0 37  0  0  0  0  0]
 [ 0  0  0  0 35  0  0 35  0  0 35  0  0  0  0]
 [ 0  0  0 31  0  0  0 31  0  0  0 31  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]


The value of a lonely totally free stone, here it's from the stone's owner, which is the 'other' player.

In [35]:
np.sum(v1)

1.1458299

In [36]:
def values(board):

    res = detector(expand(board))
    # images of the fourty filters
    v = [np.squeeze(peel(tf.expand_dims(res[:, :, :, l], -1))) for l in range(40)]

    return [
        np.sum(
            sum([
                sum([
                    v[8 * s + 4 * channel + d] ** 6
                    for s in range(5)
                ])**(5/6.)
                for d in range(4)
            ]) ** (1/5)
        ) / 32.
        for channel in range(2)
    ]

In [37]:
values(board)

[0.0, 1.1458299160003662]

In [38]:
board = GomokuBoard(board_size=BOARD_SIZE, stones = 'H8G9I9I8G7F6H7F7H6')
board = GomokuBoard(board_size=BOARD_SIZE, stones = 'H8')
board.plot()

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 9    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 8    .  .  .  .  .  .  . [X] .  .  .  .  .  .  .    
 7    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 6    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 5    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O


In [62]:
from aegomoku.policies.topological_value import TopologicalValuePolicy

policy = TopologicalValuePolicy(kappa_s=6, kappa_d=5)
st = 'H8G9I9I8G7F6H7F7H6'
board = GomokuBoard(board_size=BOARD_SIZE, stones = st)
board.plot()
state = board.canonical_representation()
f_c = (policy.field(state, channel=0)*100).astype(int)
f_o = (policy.field(state, channel=1)*100).astype(int)
p = f_o + f_c
# print(tf.keras.activations.relu(p - (np.max(p) * .3).astype(int)).numpy())
def probs():
    f_c = policy.field(state, channel=0)
    f_o = policy.field(state, channel=1)
    signal = f_o + f_c
    signal = np.reshape(signal, -1)
    signal = tf.keras.activations.relu(tf.keras.layers.Softmax()(2 * signal))
    noise = np.min(signal, axis=None)
    signal = tf.keras.activations.relu(signal - 1.1 * noise)
    return np.reshape(signal, [BOARD_SIZE, BOARD_SIZE])

print((probs()*1000).astype(int))

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 9    .  .  .  .  .  .  O  .  X  .  .  .  .  .  .    
 8    .  .  .  .  .  .  .  X  O  .  .  .  .  .  .    
 7    .  .  .  .  .  O  X  X  .  .  .  .  .  .  .    
 6    .  .  .  .  .  O  . [X] .  .  .  .  .  .  .    
 5    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O
[[  0   0   0   0   0   0   0   

In [63]:
probs, v = policy.evaluate(state)

In [64]:
print((np.reshape(probs, (BOARD_SIZE, BOARD_SIZE))*999).astype(int))
print(v)

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   1   0   1   0   7   0   0   0   0]
 [  0   0   0   0   0   0   0  89   1   7   0   0   0   0   0]
 [  0   0   0   0  13  16   0 266   0   1   0   0   0   0   0]
 [  0   0   0   1   1 254   3   0   0   2   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   7  11   0   0   0   0   0]
 [  0   0   0   0   0   0   3   0   1   0   1   0   0   0   0]
 [  0   0   0   0   0  14   3 157  14   0   0   0   0   0   0]
 [  0   0   0   0   0  15   0  78   0   1   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]]
tf.Tensor(-0.2551442921915841, shape=(), dtype=float64

In [61]:
advice = policy.get_advisable_actions(state)
[board.Stone(i) for i in advice]

[H10, H9, I9, F8, G8, G7, E9, L4]

In [ ]:
all_but_noise = policy.get_advisable_actions(state, cut_off=0)

In [86]:
secondary = set(all_but_noise).difference(set(best))

In [90]:
print(secondary)

{128, 138, 140, 141, 142, 144, 152, 154, 156, 157, 32, 160, 36, 40, 168, 172, 48, 176, 51, 52, 54, 56, 64, 66, 67, 68, 70, 80, 81, 84, 92, 93, 94, 95, 99, 100, 108, 109, 113, 114, 115, 116, 124, 127}


In [83]:
best

[82, 97, 98, 110, 111, 126]

In [89]:
tf.nn.softmax(probs[list(secondary)])

<tf.Tensor: shape=(44,), dtype=float32, numpy=
array([0.02270058, 0.02273311, 0.02275859, 0.02273311, 0.02275859,
       0.02270058, 0.02270058, 0.02273311, 0.02270058, 0.02273311,
       0.02270058, 0.02270058, 0.02270058, 0.02270058, 0.02270058,
       0.02270058, 0.02270058, 0.02270058, 0.02273311, 0.02270058,
       0.02273311, 0.02270058, 0.02270058, 0.02275859, 0.02273311,
       0.02275859, 0.02273311, 0.02270058, 0.02278058, 0.02275859,
       0.02270058, 0.02273311, 0.02275859, 0.02278058, 0.02273311,
       0.02270058, 0.02270058, 0.02273311, 0.02278058, 0.02275859,
       0.02273311, 0.02270058, 0.02275859, 0.02278058], dtype=float32)>

In [91]:
probs[list(secondary)]

array([0.00516028, 0.00659239, 0.00771268, 0.00659239, 0.00771268,
       0.00516028, 0.00516028, 0.00659239, 0.00516028, 0.00659239,
       0.00516028, 0.00516028, 0.00516028, 0.00516028, 0.00516028,
       0.00516028, 0.00516028, 0.00516028, 0.00659239, 0.00516028,
       0.00659239, 0.00516028, 0.00516028, 0.00771268, 0.00659239,
       0.00771268, 0.00659239, 0.00516028, 0.00867837, 0.00771268,
       0.00516028, 0.00659239, 0.00771268, 0.00867837, 0.00659239,
       0.00516028, 0.00516028, 0.00659239, 0.00867837, 0.00771268,
       0.00659239, 0.00516028, 0.00771268, 0.00867837], dtype=float32)

In [107]:
max_p = max(probs[list(secondary)])
secondary_probs = tf.nn.softmax(10 * probs[list(secondary)] / max_p)

In [109]:
sum_probs = sum(secondary_probs.numpy())
secondary_probs /= sum_probs

In [116]:
np.random.choice(list(secondary), size=3, p=secondary_probs)

array([ 94, 114,  81])

In [ ]:
board = GomokuBoard(board_size=BOARD_SIZE, stones = 'H8')

In [198]:
board.act(6,6).plot()
values(board)

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 9    .  .  .  .  .  . [O] .  .  .  .  .  .  .  .    
 8    .  .  .  .  .  .  .  X  .  .  .  .  .  .  .    
 7    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 6    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 5    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O


[0.9843724966049194, 0.9843724966049194]

In [199]:
board.act(6,8).plot()
values(board)

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 9    .  .  .  .  .  .  O  . [X] .  .  .  .  .  .    
 8    .  .  .  .  .  .  .  X  .  .  .  .  .  .  .    
 7    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 6    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 5    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O


[0.8656457662582397, 1.7605684995651245]

In [200]:
board.act(7,8).plot()
values(board)

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 9    .  .  .  .  .  .  O  .  X  .  .  .  .  .  .    
 8    .  .  .  .  .  .  .  X [O] .  .  .  .  .  .    
 7    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 6    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 5    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O


[1.5324900150299072, 1.596034288406372]

In [201]:
board.act(8,6).plot()
values(board)

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 9    .  .  .  .  .  .  O  .  X  .  .  .  .  .  .    
 8    .  .  .  .  .  .  .  X  O  .  .  .  .  .  .    
 7    .  .  .  .  .  . [X] .  .  .  .  .  .  .  .    
 6    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 5    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O


[1.5099903345108032, 2.205475091934204]

In [202]:
board.act(9,5).plot()
values(board)

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 9    .  .  .  .  .  .  O  .  X  .  .  .  .  .  .    
 8    .  .  .  .  .  .  .  X  O  .  .  .  .  .  .    
 7    .  .  .  .  .  .  X  .  .  .  .  .  .  .  .    
 6    .  .  .  .  . [O] .  .  .  .  .  .  .  .  .    
 5    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O


[1.8995661735534668, 2.2216696739196777]

In [203]:
board.act(8,7).plot()
values(board)

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 9    .  .  .  .  .  .  O  .  X  .  .  .  .  .  .    
 8    .  .  .  .  .  .  .  X  O  .  .  .  .  .  .    
 7    .  .  .  .  .  .  X [X] .  .  .  .  .  .  .    
 6    .  .  .  .  .  O  .  .  .  .  .  .  .  .  .    
 5    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O


[2.124302864074707, 2.6444621086120605]

In [204]:
board.act(8,5).plot()
values(board)

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 9    .  .  .  .  .  .  O  .  X  .  .  .  .  .  .    
 8    .  .  .  .  .  .  .  X  O  .  .  .  .  .  .    
 7    .  .  .  .  . [O] X  X  .  .  .  .  .  .  .    
 6    .  .  .  .  .  O  .  .  .  .  .  .  .  .  .    
 5    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O


[2.3853323459625244, 2.7530932426452637]

In [205]:
board.act(9,7).plot()
values(board)

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 9    .  .  .  .  .  .  O  .  X  .  .  .  .  .  .    
 8    .  .  .  .  .  .  .  X  O  .  .  .  .  .  .    
 7    .  .  .  .  .  O  X  X  .  .  .  .  .  .  .    
 6    .  .  .  .  .  O  . [X] .  .  .  .  .  .  .    
 5    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O


[2.669891357421875, 2.9307990074157715]

In [192]:
board.act(6,6).plot()
values(board)

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 9    .  .  .  .  .  . [O] .  .  .  .  .  .  .  .    
 8    .  .  .  .  .  .  .  X  .  .  .  .  .  .  .    
 7    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 6    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 5    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O


[0.9843724966049194, 0.9843724966049194]

In [192]:
board.act(6,6).plot()
values(board)

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 9    .  .  .  .  .  . [O] .  .  .  .  .  .  .  .    
 8    .  .  .  .  .  .  .  X  .  .  .  .  .  .  .    
 7    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 6    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 5    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O


[0.9843724966049194, 0.9843724966049194]

In [192]:
board.act(6,6).plot()
values(board)

                                                     
15    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
14    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
13    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
12    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
11    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
10    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 9    .  .  .  .  .  . [O] .  .  .  .  .  .  .  .    
 8    .  .  .  .  .  .  .  X  .  .  .  .  .  .  .    
 7    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 6    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 5    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 4    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 3    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 2    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
 1    .  .  .  .  .  .  .  .  .  .  .  .  .  .  .    
                                                     
      A  B  C  D  E  F  G  H  I  J  K  L  M  N  O


[0.9843724966049194, 0.9843724966049194]